# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_break_down_url', models.URLField()),
                ('budget_break_down_description', models.CharField(max_length=50, verbose_name='Budget Description')),
                ('budget_break_down_id', models.IntegerField()),
                ('budget_classification_level_label', models.CharField(max_length=50, verbose_name='Level Label')),
                ('budget_classification_level_description', models.CharField(max_length=50, verbose_name='Level description')),
            ],
        ),
    ]
