# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_buyer_publisher_tag_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='buyer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='analytics.Buyer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='analytics.Publisher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='analytics.Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='tender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='analytics.Tender'),
            preserve_default=False,
        ),
    ]
