# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-05 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20180404_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_with_tax', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('implementation', models.CharField(max_length=250)),
                ('suppliers', models.CharField(max_length=50)),
                ('buyers', models.CharField(max_length=50)),
                ('date_signed', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('award_id', models.CharField(max_length=50)),
                ('contract_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('contract_details', models.CharField(max_length=250)),
            ],
        ),
    ]
